# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vnf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(max_length=50)),
                ('launch_script', models.TextField(blank=True, null=True)),
                ('scripts_order', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=120)),
                ('cpu', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=1024)),
                ('disc', models.IntegerField(default=3)),
                ('provider', models.CharField(blank=True, max_length=120, null=True)),
                ('create', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True, null=True)),
                ('real_time', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
                ('scripts', models.ManyToManyField(blank=True, to='scripts.Script')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
    ]
