# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ns', '0001_initial'),
        ('bbus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('nvf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Nvf')),
                ('sinr', models.FloatField(default=0.0)),
                ('delay', models.FloatField(default=0.0)),
                ('next_nvf', models.CharField(blank=True, max_length=120, null=True)),
                ('tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbus.Bbu')),
            ],
            bases=('ns.nvf',),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('ns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Ns')),
                ('rb_offer', models.IntegerField(default=0)),
            ],
            bases=('ns.ns',),
        ),
    ]
