#!/bin/bash
# -*- ENCODING: UTF-8 -*-

cd OOCRAN/
gnome-terminal -e "bash -c 'celery -A OOCRAN worker -l info;exec $SHELL'"
gnome-terminal -e "bash -c 'celery -A OOCRAN beat -l info -S django;exec $SHELL'"
python manage.py runserver

