#!/bin/bash
# -*- ENCODING: UTF-8 -*-

cd OOCRAN/

if [ -z "$1" ]
  then
    echo "No argument supplied"
    echo "Please introduce IP:Port"
else
    if [ "$2" == "test" ]
      then
         python manage.py runserver $1
         celery -A OOCRAN worker -l info
    else
        gnome-terminal -e "bash -c 'celery -A OOCRAN worker -l info;exec $SHELL'"
        #gnome-terminal -e "bash -c 'celery -A OOCRAN beat -l info -S django;exec $SHELL'"
        #sudo service grafana-server start
        python manage.py runserver $1
    fi
fi

