#!/usr/bin/env bash

###
#    Open Orchestrator Cloud Radio Access Network
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
###


function dependencies {
    cd install
    ./dependencies.sh
    exit
}

function server {
    echo "Install OOCRAN server!"
    echo ""
    #Install dependecies
    pip install -r requirements.txt
    #Change secret key
    python install/key.py
    cd OOCRAN
    #Create database
    python manage.py makemigrations
    python manage.py migrate
    #Create admin User
    CODE=""
    while read line
    do
        CODE="$CODE$line;"
    done < ../install/create_admin.py
    echo "$CODE" | python manage.py shell &> /dev/null
    echo ""
    echo "Installation Finished!!"
    echo "Write oocran start IP:PORT to start server."
    exit
}

function install {
    if [ -z $PARAM ];
      then
        echo "No argument supplied"
        echo "Please introduce service"
        echo "ex: ./oocran install server"
        echo "ex: ./oocran install dependencies"
        exit
    else
        if [ "$PARAM" == "server" ]
          then
            server
        elif [ "$PARAM" == "dependencies" ]
          then
            dependencies
        fi
    fi
}

function reset {
    cd development && ./resetdb.sh
    echo "OOCRAN reset done!"
}

function start {
    echo "Starting OOCRAN server ;)"
    cd OOCRAN/
    if [ -z $PARAM ];
      then
        echo "No argument supplied"
        echo "Please introduce IP:Port"
        exit
    else
        #gnome-terminal -e "bash -c 'celery -A oocran worker -l info;exec $SHELL'"
        #gnome-terminal -e "bash -c 'celery -A oocran beat -l info -S django;exec $SHELL'"
        #gnome-terminal -e "bash -c 'influxd;exec $SHELL'"
        if [ -z "$LOG" ]
        then
            celery -A oocran worker -l info &>> log/worker.log &
            celery -A oocran beat -l info -S django &>> log/scheduler.log &
            echo "username: admin"
            echo "password: admin"
            python manage.py runserver $PARAM
        else
            celery -A oocran worker -l info &>> "$LOG/worker.log" &
            celery -A oocran beat -l info -S django &>> "$LOG/scheduler.log" &
            echo "username: admin"
            echo "password: admin"
            python manage.py runserver $PARAM
        fi
    fi
}


if [ -z "$1" ];
    then
        echo "Command not found!"
        echo "./oocran [command] [parameters]"
        exit
else

    OPTION=$1
    PARAM=$2
    LOG=$3

    case "$1" in
       install) install
          ;;
       start) start
          ;;
       reset) reset
          ;;
       *) echo "Order Not Found"
          ;;
    esac
fi

