# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('ip', models.CharField(max_length=120)),
                ('latitude', models.FloatField(max_length=120)),
                ('longitude', models.FloatField(max_length=120)),
                ('username', models.CharField(default='admin', max_length=120)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('project_domain', models.CharField(default='default', max_length=120)),
                ('project', models.CharField(default='admin', max_length=120)),
                ('public_network', models.CharField(default='network', max_length=120)),
                ('domain', models.CharField(default='default', max_length=120)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
