# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('nvfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epc',
            fields=[
                ('nvfi_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nvfis.NVFI')),
                ('heat', models.TextField(blank=True, null=True)),
            ],
            bases=('nvfis.nvfi',),
        ),
    ]
