# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ns', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBU',
            fields=[
                ('nvf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Nvf')),
                ('freC_DL', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('color_DL', models.CharField(blank=True, default='#AA0000', max_length=20, null=True)),
                ('bw_dl', models.IntegerField(blank=True, default=20, null=True)),
                ('rb', models.IntegerField(blank=True, default=20, null=True)),
                ('pt', models.FloatField(blank=True, default=20, null=True)),
                ('freC_UL', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('color_UL', models.CharField(blank=True, default=20, max_length=20, null=True)),
                ('bw_ul', models.IntegerField(blank=True, default=20, null=True)),
                ('radio', models.CharField(blank=True, default=0, max_length=120, null=True)),
                ('rrh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.RRH')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
            bases=('ns.nvf',),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('nvf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Nvf')),
                ('sinr', models.FloatField(default=0.0)),
                ('delay', models.FloatField(default=0.0)),
            ],
            bases=('ns.nvf',),
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('nvf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Nvf')),
                ('sensibility', models.FloatField(default=0.0)),
                ('service', models.FloatField(default=3600)),
                ('delay', models.FloatField(default=0.0)),
            ],
            bases=('ns.nvf',),
        ),
        migrations.CreateModel(
            name='Utran',
            fields=[
                ('ns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Ns')),
                ('rb_offer', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            bases=('ns.ns',),
        ),
    ]
