# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('ns', '0001_initial'),
        ('scenarios', '0001_initial'),
        ('vnfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('freC_DL', models.PositiveIntegerField(blank=True, null=True)),
                ('color_DL', models.CharField(blank=True, default='#AA0000', max_length=20, null=True)),
                ('bw_dl', models.IntegerField(blank=True, null=True)),
                ('rb', models.IntegerField(blank=True, null=True)),
                ('pt', models.FloatField(blank=True, null=True)),
                ('freC_UL', models.PositiveIntegerField(blank=True, null=True)),
                ('color_UL', models.CharField(blank=True, max_length=20, null=True)),
                ('bw_ul', models.IntegerField(blank=True, null=True)),
                ('radio', models.CharField(blank=True, default=0, max_length=120, null=True)),
                ('users', models.IntegerField(blank=True, default=0, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
        migrations.CreateModel(
            name='Utran',
            fields=[
                ('ns_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='ns.Ns')),
                ('rb_offer', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='scenarios.Scenario')),
            ],
            bases=('ns.ns',),
        ),
        migrations.AddField(
            model_name='bbu',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ns.Ns'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='rrh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenarios.RRH'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='vnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vnfs.Vnf'),
        ),
    ]
