# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('nvfis', '0001_initial'),
        ('scenarios', '0001_initial'),
        ('vnfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('load', models.CharField(max_length=400)),
                ('freC_DL', models.IntegerField(blank=True, null=True)),
                ('color_DL', models.CharField(blank=True, default='#AA0000', max_length=20, null=True)),
                ('bw_dl', models.IntegerField(blank=True, null=True)),
                ('rb', models.IntegerField(blank=True, null=True)),
                ('pt', models.FloatField(blank=True, null=True)),
                ('freC_UL', models.IntegerField(blank=True, null=True)),
                ('color_UL', models.CharField(blank=True, max_length=20, null=True)),
                ('bw_ul', models.IntegerField(blank=True, null=True)),
                ('radio', models.CharField(blank=True, default=0, max_length=120, null=True)),
                ('static_labels', models.CharField(blank=True, max_length=400, null=True)),
                ('static_cpu', models.CharField(blank=True, max_length=400, null=True)),
                ('static_ram', models.CharField(blank=True, max_length=400, null=True)),
                ('static_net', models.CharField(blank=True, max_length=400, null=True)),
                ('users', models.IntegerField(blank=True, default=0, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AWGN', max_length=120)),
                ('ip', models.CharField(max_length=20)),
                ('snr', models.FloatField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pt_dl', models.FloatField()),
                ('pt_ul', models.FloatField()),
                ('lat', models.CharField(max_length=120)),
                ('longi', models.CharField(max_length=120)),
                ('dist', models.CharField(max_length=120)),
                ('rb', models.IntegerField(blank=True, null=True)),
                ('mcs', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nvf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbus.BBU')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
        migrations.CreateModel(
            name='Utran',
            fields=[
                ('nvfi_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='nvfis.NVFI')),
                ('rb_offer', models.IntegerField(default=0)),
            ],
            bases=('nvfis.nvfi',),
        ),
        migrations.AddField(
            model_name='ue',
            name='nvfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvfis.NVFI'),
        ),
        migrations.AddField(
            model_name='ue',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator'),
        ),
        migrations.AddField(
            model_name='channel',
            name='nvfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvfis.NVFI'),
        ),
        migrations.AddField(
            model_name='channel',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator'),
        ),
        migrations.AddField(
            model_name='channel',
            name='vnf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vnfs.Vnf'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='nvfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nvfis.NVFI'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='rrh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenarios.RRH'),
        ),
        migrations.AddField(
            model_name='bbu',
            name='vnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vnfs.Vnf'),
        ),
    ]
