# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbu',
            name='static_cpu',
        ),
        migrations.RemoveField(
            model_name='bbu',
            name='static_labels',
        ),
        migrations.RemoveField(
            model_name='bbu',
            name='static_net',
        ),
        migrations.RemoveField(
            model_name='bbu',
            name='static_ram',
        ),
    ]
