# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bbus', '0002_auto_20170126_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbu',
            name='load',
        ),
    ]
