# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bbus', '0004_auto_20170126_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='nvfi',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='vnf',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='nvf',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='nvfi',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='UE',
        ),
    ]
