# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nvfis', '0002_remove_nvfi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvfi',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
