# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nvfis', '0003_nvfi_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvfi',
            name='vim',
            field=models.CharField(default='Near', max_length=120),
        ),
    ]
