# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('nfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vnf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=120)),
                ('create', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nf', models.ManyToManyField(blank=True, to='nfs.Nf')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
            ],
            options={
                'ordering': ['-timestamp', '-update'],
            },
        ),
    ]
