# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vnfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnf',
            name='create',
            field=models.BooleanField(default=False),
        ),
    ]
