# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ns', '0001_initial'),
        ('bbus', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('nvf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ns.Nvf')),
                ('sensibility', models.FloatField()),
                ('service', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('attached_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbus.Bbu')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario')),
            ],
            bases=('ns.nvf',),
        ),
    ]
