# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nf',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
